### PR TITLE
Sidehotfix 0.0.9

### PR DESCRIPTION
**Pull request by Duelsik**

### CODE REVIEW

**Comment by zaourzag** [comment]
I think you forgot to implement #11 and are now still using the old api for 0.0.9 😅

**Comment by zaourzag** [comment]
@Duelsik 
Screenshot_20220224-110338_Discord-Beta I'd recommend using the new api lol

**Comment by Duelsik** [comment]
This change rendered to be more complicated than changing strings in the code, I have that in my backlog.

**Comment by zaourzag** [comment]
> This change rendered to be more complicated than changing strings in the code, I have that in my backlog.

How come? Maybe I can help?

**Comment by Duelsik** [comment]
I have to setup something like https://github.com/BarryCarlyon/twitchextensioncsp for this repo, generally it is about not running into problems with twitch security update.

**Pull request merged**
