### PR TITLE
(fix) Update due to new bestsaver api

### PR DESCRIPTION
**Pull request by Danielduel**

### CODE REVIEW

**Comment by zaourzag** [comment]
okay! np dude! the new api broke everything. due to a change in owners the system got completely revamped

**Comment by Duelsik** [comment]
@zaourzag technically extension is broken because twitch changed their CSP rules.
(you can sort of read more here https://dev.twitch.tv/docs/extensions/#security-model)
But I don't mind updating domain to the new one :)
Maybe it will be a good time to fix beatfollower images too KEKW

**Comment by zaourzag** [comment]
Yeah I noticed. Due to new beatsaver api. And also new beatfollower api it seems. Which completely breaks it. As in it is their fault partly

**Comment by zaourzag** [comment]
And thats why we dont do static domains lmao. Beatfollower takes from two sources: beatsaver and another one.

**Pull request merged**
